services:
  reverse-proxy:
    restart: always
    image: docker.milad.ir/traefik:3.4.0-rc2
    command:
      - --log.level=DEBUG
      - --log.filepath=/log-file.log
      - --log.format=json
      - --api=true
      - --ping=true
      - --accesslog=true
      - --accesslog.bufferingsize=100
      - --api.insecure=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=web_net
      - --entrypoints.http.address=:80
      - --entryPoints.web.transport.respondingTimeouts.readTimeout=3600
      - --entryPoints.name.transport.respondingTimeouts.writeTimeout=3600
      - --entryPoints.web.transport.respondingTimeouts.idleTimeout=3600
      - --entryPoints.name.transport.lifeCycle.requestAcceptGraceTimeout=3600
    ports:
      - "80:80"
        #      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-dynamic:/etc/traefik/dynamic

    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web_net"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.milad.ir`)"
      - "traefik.http.services.traefik-secure.loadbalancer.server.port=8080"
        # 4GB max body for docker images - must apply to each service
      - "traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=4000000000"
      - "traefik.http.middlewares.limit.buffering.maxResponseBodyBytes=4000000000"
      - "traefik.http.middlewares.limit.buffering.memResponseBodyBytes=2000000"
      - "traefik.http.middlewares.limit.buffering.memRequestBodyBytes=2000000"

 
  new-nexus:
    image: sonatype/nexus3:3.79.1-java17-alpine
    volumes:
      - "new-nexus-data:/sonatype-work"
    dns:
      - 178.22.122.101
      - 185.51.200.1

    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web_net"
        #newnexus
      - "traefik.http.routers.newnexus.entrypoints=http"
      - "traefik.http.routers.newnexus.rule=Host(`newnexus.milad.ir`)"
      - "traefik.http.routers.newnexus.service=newnexus-web"
      - "traefik.http.services.newnexus-web.loadbalancer.server.port=8081"
                            #NewNexus-HostedDocker
      - "traefik.http.routers.registry.entrypoints=http"
      - "traefik.http.routers.registry.rule=Host(`registry.milad.ir`)"
      - "traefik.http.routers.registry.service=repo-registry"
      - "traefik.http.services.repo-registry.loadbalancer.server.port=5005"
        #newNexus-Docker-Group
      - "traefik.http.routers.nexusdocker.entrypoints=http"
      - "traefik.http.routers.nexusdocker.rule=Host(`docker.milad.ir`)"
      - "traefik.http.routers.nexusdocker.service=nexusdocker-secure"
      - "traefik.http.services.nexusdocker-secure.loadbalancer.server.port=5002"


 # nexus:
  #         #image: sonatype/nexus3:3.41.0
  #   image: sonatype/nexus3:3.70.1
  #   volumes:
  #     - "../nexusData:/nexus-data"
  #   restart: always
  #   ports:
  #     - "8081:8081"
  #     - "5000:5000"
  #     - "5001:5001"
  #     - "5002:5002"
  #     - "5003:5003"
  #     - "5004:5004"
  #   networks:
  #     - default
  #   dns:
  #     - 178.22.122.101
  #     - 185.51.200.1
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.docker.network=web_net"
  #     - "traefik.http.routers.repo.entrypoints=http"
  #     - "traefik.http.routers.repo.rule=Host(`repo.milad.ir`)"
  #     - "traefik.http.routers.repo.service=repo-secure"
  #     - "traefik.http.services.repo-secure.loadbalancer.server.port=8081"
  #     - "traefik.http.middlewares.limit.buffering.memRequestBodyBytes=3000000"
  #     - "traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=3000000"
  #       #registry

  #       #- "traefik.http.routers.tab17.entrypoints=http"
  #       #- "traefik.http.routers.tab17.rule=Host(`repo2.sayandc.dc`)"
  #       #- "traefik.http.routers.tab17.service=tab17-secure"
  #       #- "traefik.http.services.tab17-secure.loadbalancer.server.port=8084"
  #       #- "traefik.http.middlewares.limit.buffering.memRequestBodyBytes=3000000"
  #       #- "traefik.http.middlewares.limit.buffering.memRequestBodyBytes=3000000"


  #     # Increase timeout settings for Traefik services
  #     - "traefik.http.services.repo.loadbalancer.responseForwarding.flushInterval=2000ms"
  #     - "traefik.http.services.nexusdocker.loadbalancer.responseForwarding.flushInterval=2000ms"
  #     - "traefik.http.services.nexusdocker2.loadbalancer.responseForwarding.flushInterval=2000ms"
networks:
  default:
    name: nexus_net
volumes:
  nexus-data: {}
  traefik-dynamic: {}
  new-nexus-data: {}
